version: "3.3"
services:
  database:
    image: mysql:latest
    restart: always
    container_name: mysql-app
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - thinktank-mysql-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: thinktank-app
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ec2-user/IdeaProjects/ThinkTank_BE/tmp:/tmp
    networks:
      - thinktank-mysql-net

volumes:
  code_volume:
    driver: local

networks:
  thinktank-mysql-net:
    driver: bridge
