version: "3.3"
services:
  database:
    image: mysql:latest
    restart: always
    container_name: mysql-app
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - thinktank-mysql-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: thinktank-app
    privileged: true   # Privileged 모드 활성화
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/mysql?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JWT_SECRET_ACCESS_KEY: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
      SPRING_JWT_ACCESS_EXPIRE: 86400000
      SHARED_PATH: /tmp

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ec2-user/IdeaProjects/ThinkTank_BE/tmp:/tmp
      - /home/ec2-user/IdeaProjects/ThinkTank_BE/temp:/app

    networks:
      - thinktank-mysql-net

volumes:
  code_volume: # 이미 있는 볼륨 설정을 활용
    driver: local

networks:
  thinktank-mysql-net:
    driver: bridge
