jwt:
  secret:
    access-key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  #access-expire: 10_000  # 10 sec
  access-expire: 300_000 # 5 min
  refresh-expire: 604_800_000 # 7 days

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-think

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/think
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:

        registration:
          kakao:
            client-id: { KAKAO_CLIENT_ID }
            client-secret: { KAKAO_CLIENT_SECRET }
            redirect-uri: http://localhost:8080/oauth/authorize/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname, account_email

          google:
            client-id: { GOOGLE_CLIENT_ID }
            client-secret: { GOOGLE_CLIENT_SECRET }
            scope: email, profile
            redirect-uri: http://localhost:8080/oauth/authorize/google
            client-name: Google

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

